spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study_project_demo1?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 20041114Liuyu!
  mail:
    host: smtp.163.com
    username: Jade0v0@163.com
    password: HUfnrH6Pxiu8j4zk
    properties:
      from: Jade0v0@163.com

  data:
    redis:
      database: 0
      host: localhost
      port: 6379
